/**
 * Configuration File Templates
 * 
 * Templates for generating configuration files.
 */

import { ProjectPlan } from '../../planning';

export function generatePackageJson(plan: ProjectPlan): string {
  const deps: Record<string, string> = {};
  const devDeps: Record<string, string> = {};

  plan.dependencies.forEach(dep => {
    if (dep.type === 'dependency') {
      deps[dep.name] = dep.version;
    } else {
      devDeps[dep.name] = dep.version;
    }
  });

  return JSON.stringify({
    name: plan.name,
    version: '0.1.0',
    private: true,
    type: 'module',
    scripts: {
      dev: 'vite',
      build: 'tsc && vite build',
      preview: 'vite preview',
      lint: 'eslint . --ext ts,tsx --report-unused-disable-directives --max-warnings 0'
    },
    dependencies: deps,
    devDependencies: devDeps
  }, null, 2);
}

export function generateTsConfig(): string {
  return JSON.stringify({
    compilerOptions: {
      target: 'ES2020',
      useDefineForClassFields: true,
      lib: ['ES2020', 'DOM', 'DOM.Iterable'],
      module: 'ESNext',
      skipLibCheck: true,
      moduleResolution: 'bundler',
      allowImportingTsExtensions: true,
      resolveJsonModule: true,
      isolatedModules: true,
      noEmit: true,
      jsx: 'react-jsx',
      strict: true,
      noUnusedLocals: true,
      noUnusedParameters: true,
      noFallthroughCasesInSwitch: true
    },
    include: ['src'],
    references: [{ path: './tsconfig.node.json' }]
  }, null, 2);
}

export function generateViteConfig(plan: ProjectPlan): string {
  return `import { defineConfig } from 'vite';
import react from '@vitejs/plugin-react';

// https://vitejs.dev/config/
export default defineConfig({
  plugins: [react()],
  server: {
    port: ${plan.buildConfig.devServer?.port || 5173},
    host: '${plan.buildConfig.devServer?.host || 'localhost'}',
    open: true
  },
  build: {
    outDir: '${plan.buildConfig.output}',
    sourcemap: true
  }
});
`;
}

export function generateTailwindConfig(): string {
  return `/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {},
  },
  plugins: [],
}
`;
}

export function generatePostCSSConfig(): string {
  return `export default {
  plugins: {
    tailwindcss: {},
    autoprefixer: {},
  },
}
`;
}

export function generateGitIgnore(): string {
  return `# Logs
logs
*.log
npm-debug.log*
yarn-debug.log*
yarn-error.log*
pnpm-debug.log*
lerna-debug.log*

node_modules
dist
dist-ssr
*.local

# Editor directories and files
.vscode/*
!.vscode/extensions.json
.idea
.DS_Store
*.suo
*.ntvs*
*.njsproj
*.sln
*.sw?
`;
}

export function generateIndexHtml(plan: ProjectPlan): string {
  return `<!doctype html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <link rel="icon" type="image/svg+xml" href="/vite.svg" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>${plan.name}</title>
  </head>
  <body>
    <div id="root"></div>
    <script type="module" src="/src/main.tsx"></script>
  </body>
</html>
`;
}

export function generateReadme(plan: ProjectPlan): string {
  return `# ${plan.name}

${plan.description}

## Features

${plan.understanding.features.map(f => `- ${f.description}`).join('\n')}

## Tech Stack

${plan.understanding.technologies.map(t => `- **${t.name}**: ${t.reason}`).join('\n')}

## Getting Started

### Prerequisites

- Node.js 18+ 
- npm or yarn

### Installation

\`\`\`bash
# Install dependencies
npm install

# Start development server
npm run dev

# Build for production
npm run build
\`\`\`

## Project Structure

\`\`\`
${plan.name}/
├── src/
│   ├── components/     # React components
│   ├── pages/          # Page components
│   ├── layouts/        # Layout components
│   ├── hooks/          # Custom hooks
│   ├── stores/         # State management
│   ├── utils/          # Utility functions
│   └── types/          # TypeScript types
├── public/             # Static assets
└── index.html          # Entry HTML
\`\`\`

## Development

This project was generated by **Orix-AI** - an AI-native autonomous development environment.

## License

MIT

---

Generated with ❤️ by Orix-AI
`;
}

// Made with Bob